services:
  api:
    command:
      - fastapi
      - dev
      - app/main.py
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - "**/__pycache__/"
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./Dockerfile
