services:
  api:
    secrets:
      - source: FDP_ORACLE__CREDENTIALS__USER
        target: FDP_ORACLE__CREDENTIALS__USER
      - source: FDP_ORACLE__CREDENTIALS__PASSWORD
        target: FDP_ORACLE__CREDENTIALS__PASSWORD
      - source: FDP_ADB__CREDENTIALS__USER
        target: FDP_ADB__CREDENTIALS__USER
      - source: FDP_ADB__CREDENTIALS__PASSWORD
        target: FDP_ADB__CREDENTIALS__PASSWORD

secrets:
  FDP_ORACLE__CREDENTIALS__USER:
    file: ./.secrets/FDP_ORACLE__CREDENTIALS__USER
  FDP_ORACLE__CREDENTIALS__PASSWORD:
    file: ./.secrets/FDP_ORACLE__CREDENTIALS__PASSWORD
  FDP_ADB__CREDENTIALS__USER:
    file: ./.secrets/FDP_ADB__CREDENTIALS__USER
  FDP_ADB__CREDENTIALS__PASSWORD:
    file: ./.secrets/FDP_ADB__CREDENTIALS__PASSWORD
